# Render Blueprint for Lost and Found API
services:
  - type: web
    name: lost-found-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DATABASE_NAME
        value: lost_and_found
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
